[build]
  command = ""
  publish = "."
  functions = "non-existent-folder" # Forces static site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false

[plugins]
  enabled = false # Disables ALL plugins
